### ISSUE TITLE
Missing training details. What's the train/dev/test split for BaiduZhidao? Any data release plan?

### ISSUE THREAD

**Issue by freesunshine0316** [ningningyang/NDPR#1]

**Comment by ningningyang** [comment]
I will add the training details of BaiduZhidao in Readme file in next several days. The datasets maybe will not be released due to copyright problem.

**Comment by stellarway** [comment]
Can you give me an example of how the data is formatted?
It is difficult to know the difference between labelg and labeli or the difference between data and data_part.
