### ISSUE TITLE
Two typos in the code

### ISSUE THREAD

**Issue by freesunshine0316** [ningningyang/NDPR#2]
Hi, Just want to share the two typos I found in your code, which causes compiling errors.
(1)
https://github.com/ningningyang/NDPR/blob/master/train_v4.py#L36
False --> 0
(2)
https://github.com/ningningyang/NDPR/blob/master/train_v4.py#L38
flags.DEFINE_integer --> flags.DEFINE_float

**Comment by ningningyang** [comment]
Thanks for pointing out these two typos. I have modified them in current version.
